### ISSUE TITLE
Responsive Components: switch all theme CSS rules from px to em

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#1070]
strategy: we need to start with font-sizes, since the base unit (font-size) should be 16px for all components.

afterwards: 1em == 16px => convert the values.

exception: borders need to stay px based.

a pretty big, but trivial ticket. we should split it up as needed.

i will probably refactor component.DateSelector very soon.

**Comment by TatisLois** [comment]
Hey @tobiu seems like a straightforward but tedious task, probably a great candidate to get familiar with the codebase. 

Is this something I can take up? :)

**Comment by tobiu** [comment]
Welcome @TatisLois,

to get familiar with the code base, I recommend to take a look at the 2 covid app tutorials first:

https://neomjs.github.io/pages/node_modules/neo.mjs/dist/production/apps/website/index.html#mainview=blog

=> https://medium.com/swlh/how-to-create-a-webworkers-driven-multithreading-app-part-1-fa0cc78a4237?source=friends_link&sk=a10ca85002f5f9c3ee8c69f53c79d95f

Of course, help on this ticket is greatly appreciated. I would create new related tickets to keep it reasonable, e.g. button.Base: em based styling.

I am working on drag&drop support for lists & tree lists next, since I need this one for a client project.

Best regards,
Tobias
