### ISSUE TITLE
Neo.dialog.Toast

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#1087]
Could be a good first issue, since a lot of toast message implementations are already out there and creating the animations should be fun.

We could extend the Dialog Class.

We probably want to use a manager class as well.

Toast Messages need a timeout config, closable (timeout:0), position (tr, tc, br,...), a slide in direction (e.g. in case they appear at the top right edge of the screen, it should be possible to slide them in from the top or right side).

Once the timeout ends => fadeOut.

As the name suggests, toast messages can stack.

**Comment by tobiu** [comment]
another option to keep it more lightweight is extending component.Base.

**Comment by Dinkh** [comment]
Solved in #3800
