### ISSUE TITLE
Project will not build on windows machines, nothing in dist folder

### ISSUE THREAD

**Issue by nick-d-dev** [neomjs/neo#1175]
**Describe the bug**
There is no working build on windows machines.

**To Reproduce**
1. Checkout the project
2. do npm run install
3. do npm run build-all
4. do npm run server-start

**Expected behavior**
The project builds correctly with all the code and CSS

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85 (latest/any)

**Additional context**
Windows has specific path resolving issues that are not addressed

**Comment by tobiu** [comment]
Hi Nick and welcome to the community!

Thx for the PR, I have not tested builds on windows in ages. It did work before adding the build programs, but this was quite a while back.

I think we don't need the new webpackResolvedPath variable.

```
if (process.platform === "win32") {
        // due to specific windows pathing we must do a lil bit of hackery to get it to build properly
        // functionality on linux/mac remains unchanged
        webpack = path.resolve(webpack).replace(/\\/g,'/');
    }
```

should do the same. I might do this minor cleanup, does not really matter though inside the build tools.

**Comment by tobiu** [comment]
Just out of curiosity: What would happen in case you are using Windows, but with a Linux Kernel? This might require slashes instead of backslashes again.

Well, I am definitely not a Windows guy, so no clue.

**Comment by nick-d-dev** [comment]
yeah, you're right, its just a habit from years of working in my current
company to declare a new variable always rather than using the old one.

///

as for the linux kernel, are you referring to the linux subsystem that is
on windows 10?

honestly, i wouldn't know, i never used it, i actually dual boot between
linux and windows when i need to : /

**Comment by tobiu** [comment]
Meant this one: https://linuxhint.com/linux_kernel_windows10/

Well, let's assume using it changes process.platform in node. If not, there will be a new ticket for sure.

Feel free to jump into the Slack Channel in case you have any questions on neo in general. The vdom concept can be a bit confusing at first.

Best regards, Tobias
