### ISSUE TITLE
Migrate to webpack version 5

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#1385]
Since webpack 5 is stable now (no longer RC), we should migrate at some point soon-ish.

We need to adjust the related build scripts:
https://github.com/neomjs/neo/tree/dev/buildScripts/webpack

Plus double-check, if the external plugins we are using still work.

I am flagging the ticket as a "good first issue", since you can work on it without having knowledge about this framework.

I am also flagging it as "help wanted", since I am busy with polishing the new drag&drop implementation.

**Comment by h1b9b** [comment]
Hello, As there is no breaking changes. I made a [PR](https://github.com/neomjs/neo/pull/1465) upgrading webpack to version 5.
