### ISSUE TITLE
Images missing in docs examples

### ISSUE THREAD

**Issue by diplopito** [neomjs/neo#187]
**Describe the bug**
Images in documentation are missing (broken)

**To Reproduce**
1. Go to https://neomjs.github.io/pages/node_modules/neo.mjs/dist/production/docs/index.html
2. Click on 'Tutorias -> create-app script'
3. Scroll down to '1. After running the script, you will get asked to...

**Comment by tobiu** [comment]
thx for the heads up, i will look into it.

**Comment by tobiu** [comment]
fixed (on gh-pages & locally).

Hint: the local docs using the chrome flag are better, since they do include the examples.
