### ISSUE TITLE
Can't read the blog post announcement of v2

### ISSUE THREAD

**Issue by warpech** [neomjs/neo#1958]
It feels bad to report it as an issue in the repo, but the blog post announcement published at https://itnext.io/the-webworkers-driven-ui-framework-neo-mjs-version-2-release-announcement-b91b476d6f16 crashes for me in all of my browsers (Firefox, Brave, Chrome) and I really want to read it.

![image](https://user-images.githubusercontent.com/566463/117215648-cf879600-adfe-11eb-8eea-9da7fad1af20.png)

**Comment by tobiu** [comment]
Thanks for the info!

The link in general is correct. I had some problems with Medium as well during the last days.
A lot of JS errors.

Please let me know in case it still does not work tomorrow. I could recreate the article on e.g. dev.to in this case (after I am done with the current sprint).

Best regards,
Tobias

P.S.: Feel free to use a friends link. The neo online examples contain friend links for all articles.

https://itnext.io/the-webworkers-driven-ui-framework-neo-mjs-version-2-release-announcement-b91b476d6f16?source=friends_link&sk=e6eb21f75475f431ad9215d63a44fb53

**Comment by warpech** [comment]
Thanks for the fix, it loads well now! 

I am not a user of your framework (yet?), but I think it is an awesome idea and I follow all of the announcements.

TIL about Medium's friends links, too. Thanks for that :)

**Comment by tobiu** [comment]
Well, I did not fix Medium xD

In case you want to try neo, hop into the slack channel for questions (invite link at the bottom of the main readme).
Limited time on my end, but I do enjoy pointing devs into the right direction.

Literally everyone hits the point "window and (window.)document are undefined".

Best regards,
Tobias
