### ISSUE TITLE
Example examples/form/field/date/ not displaying final week of month

### ISSUE THREAD

**Issue by keckeroo** [neomjs/neo#2111]
**Describe the bug**
Month picker view is not tall enough to display all weeks of a month

**Screenshots**
![Screen Shot 2021-05-22 at 2 49 48 PM](https://user-images.githubusercontent.com/1653769/119239164-ff2be300-bb0c-11eb-8125-22b0be1bd02a.png)

**Comment by tobiu** [comment]
good catch! 6 rows is an edge case i did not encounter yet.
