### ISSUE TITLE
examples/form/field/email/ permits invalid syntax (name@something)

### ISSUE THREAD

**Issue by keckeroo** [neomjs/neo#2113]
**Describe the bug**
The email validator is permitting invalid email syntax of 'name@domain' (without the TLD)

![Screen Shot 2021-05-22 at 2 53 33 PM](https://user-images.githubusercontent.com/1653769/119239284-b58fc800-bb0d-11eb-8ddc-efd14c84ab1c.png)

**Comment by tobiu** [comment]
https://en.wikipedia.org/wiki/Email_address#Examples

![Screenshot 2021-06-03 at 20 50 53](https://user-images.githubusercontent.com/1177434/120696965-723e3d80-c4ad-11eb-8d9e-1b930fd05120.png)

by default, `<input type="email">` will allow local domains. most of the time it makes little sense (except for intranet apps).

we can add a custom validator on the JS side.
