### ISSUE TITLE
examples/form/field/picker/ displays empty picker

### ISSUE THREAD

**Issue by keckeroo** [neomjs/neo#2114]
**Describe the bug**
Picker is empty, no console error

![Screen Shot 2021-05-22 at 3 03 14 PM](https://user-images.githubusercontent.com/1653769/119239460-dc9ac980-bb0e-11eb-9cce-7a82eb399056.png)

**Comment by tobiu** [comment]
this is correct. a picker is a base class which has no content.

e.g. a date picker extends it (or a select field => adding a list).

you could add something in there for the example itself, if you to.
