### ISSUE TITLE
Textarea field resize should be anchored to top/left

### ISSUE THREAD

**Issue by keckeroo** [neomjs/neo#2117]
**Describe the bug**
When resizing textarea field, it appears that this will grow in height in BOTH directions as the resize icon is dragged. This can lead to input area affecting items above it (shoving up) and well as the input itself going above the screen and out of view

As well - the border separating the clearable icon has a gap when resizing 

**To Reproduce**
1. Go to textarea example
2. Click on resize and drag icon to resize

**Expected behavior**
The drag should be creating a bottom/right anchor for the the input area and not affect the top/left position
![Screen Shot 2021-05-22 at 3 15 01 PM](https://user-images.githubusercontent.com/1653769/119239786-f5a47a00-bb10-11eb-9132-f33934cba3ba.png)
![Screen Shot 2021-05-22 at 3 15 20 PM](https://user-images.githubusercontent.com/1653769/119239793-fc32f180-bb10-11eb-88a2-3de85831fa35.png)

**Comment by tobiu** [comment]
Changing this one to a feature request.

My labeling strategy:
Is a feature implemented but does not work? => Bug
Is it not implemented yet? => Feature Request

You are welcome to work on this one :)

**Comment by shilpeePrasad** [comment]
Hi, I would like to work on this issue. Thanks

**Comment by tobiu** [comment]
Appreciated! Feel free to join the Slack Channel in case you need help getting up to speed with neo.
