### ISSUE TITLE
Timefield example has validation inconsistent with time picker items

### ISSUE THREAD

**Issue by keckeroo** [neomjs/neo#2118]
**Describe the bug**
Need to update either the picker data or the picker mask so that picker items are valid

**To Reproduce**
1. Go to time example
2. select value
3. See error

DeltaUpdates.mjs:166 The specified value "08:05 AM" does not conform to the required format.  The format is "HH:mm", "HH:mm:ss" or "HH:mm:ss.SSS" where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.

![Screen Shot 2021-05-22 at 3 31 02 PM](https://user-images.githubusercontent.com/1653769/119240010-becf6380-bb12-11eb-84b4-42733f9d7a81.png)

**Comment by tobiu** [comment]
Hi Kevin, I need more input on this one.

![Screenshot 2021-05-22 at 23 19 32](https://user-images.githubusercontent.com/1177434/119241070-3a053980-bb54-11eb-9b6f-af0e9a35a5df.png)

Maybe a local timezone formatting issue?

**Comment by keckeroo** [comment]
Please review the image posted above. The example picker has am/pm and is probably what is causing the issue.
