### ISSUE TITLE
Field picker z-index incorrect - seems to be CSS class names being munged 

### ISSUE THREAD

**Issue by keckeroo** [neomjs/neo#241]
**Describe the bug**
The field picker appears under other items on the screen

**To Reproduce**
1. Go to fields examples
2. Click on field picker
3. Picker appears under other items on screen which overlap picker area

**Expected behavior**
Picker should always be top of z-index

**Screenshots**
<img width="280" alt="Screen Shot 2020-02-23 at 12 40 02" src="https://user-images.githubusercontent.com/1653769/75118100-91a8b280-563c-11ea-82e7-ec6fed41ba4a.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOSX
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Comment by tobiu** [comment]
Hi Kevin,

thx for the report. There is indeed something wrong inside the picker field (adding more triggers messes with the CSS class-names).

Will take a look into it, by the latest when finishing the chip-field (which is needed for the RW2 app).

Best regards,
Tobi
