### ISSUE TITLE
Double click on event results is JS error regarding invalid time format - possible TZ issue

### ISSUE THREAD

**Issue by keckeroo** [neomjs/neo#2411]
**Describe the bug**
When in week view, I double click on an event and I get the following JS error in the console :

![](https://files.slack.com/files-pri/TEK621CCA-F025FBC3TE1/screen_shot_2021-06-18_at_12.08.21.png)

**To Reproduce**
Steps to reproduce the behavior: (ensure to be in TZ other than DE)
1. Go to https://neomjs.github.io/pages/node_modules/neo.mjs/examples/calendar/basic/index.html
2. Double click on event
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version Latest

**Additional context**

**Comment by keckeroo** [comment]
![Screen Shot 2021-06-18 at 12 08 21](https://user-images.githubusercontent.com/1653769/122598378-5ea8e000-d032-11eb-88cb-fb720f4e066b.png)

**Comment by tobiu** [comment]
Thx Kevin, confirmed!
