### ISSUE TITLE
Selecting calendar date makes UI jump around trying to find a date to stop on

### ISSUE THREAD

**Issue by keckeroo** [neomjs/neo#2439]
**Describe the bug**
Clicking on a date in the calendar (when your system is not in DE) will result in calendar switching to different dates in a seemingly random fashion

**To Reproduce**
1. Ensure computer is set to a time zone other than DE
2. Go to https://neomjs.github.io/pages/node_modules/neo.mjs/examples/calendar/basic/index.html
3. Click on any day on the calendar
4. See error in console

**Expected behavior**
Calendar should change to selected date

**Screenshots**
Attached

**Desktop (please complete the following information):**
Not browser related

**Additional context**
![calendar-jump](https://user-images.githubusercontent.com/1653769/122780484-7f607800-d274-11eb-9b36-452f5639919b.gif)

**Comment by tobiu** [comment]
fixed.
