### ISSUE TITLE
Improve README and Documentation

### ISSUE THREAD

**Issue by cesar-ibr** [neomjs/neo#2724]
# What is the issue about
Right now, the project lacks of clear documentation for developers interested in the framework. The information about the framework is spread among GitHub pages and articles at Medium.

For instance, the README file is not very clear on "what exactly is neo.mjs" and "why it is needed". This might be obvious for people already involved in the project but not for new developers interested.

# How can we solve it
We already have a lot of information that @tobiu has written so maybe we just need to organize it a bit more.
The goal is to provide a fun on-boarding experience for new devs and generally, people interested in the project.

**Comment by tobiu** [comment]
definitely agree on this one.

one part which i want to add is the "no templates" topic:

using templates, we need to create the "union" of all possible states, while in neo we do create the "intersection" instead.

it creates a small overhead for simple components, but the more state related props get in there, the bigger the advantage.

**Comment by chancesmith** [comment]
I agree with @cesar-ibr. The thought leadership is there 💪, but it is a rough onboarding. So far, the dopamine has come from the medium posts by you, @tobiu. My interest is growing, but haven't cloned the repo just yet.

**Comment by tobiu** [comment]
@chancesmith: Definitely join the Slack Channel, in case you have not done this already ;)

The main readme should become like an elevator pitch, strongly focussing on the client benefits => why you should use neo.

We should also reduce the size of the main readme, but this requires to get a new learning section ready first.

Ideally, we create new markdown files inside the repo (.github folder) and also include them inside the docs app.

Topics could be:

- Class config system
- Constructing virtual dom
- Component trees
- Remotes API (remote method access)
- main thread addons
- view models
- view controllers
- more examples on how to create apps (we do have a new version of the covid app tutorial (latest blog post), but this is not enough

Best regards,
Tobias
