### ISSUE TITLE
Learning Section / Wiki

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#2776]
I will create a new project for this epic and several tickets related to it.

Please add comments or upvote the tickets of interest for you!

**Comment by aramay** [comment]
Yes, please 👍

**Comment by tobiu** [comment]
Hi @aramay,

the project already exists: https://github.com/neomjs/neo/projects/29

it has a high priority, but i will finish the service worker implementation and the circles list first.

in case there is any guide in particular, which would be helpful for you, please give me a heads up.

for now, you can dive into the blog: https://neomjs.github.io/pages/, the examples & demo apps and join the slack channel.

best regards,
tobias
