### ISSUE TITLE
Follow Selection jumps arround instead of smooth scrolling

### ISSUE THREAD

**Issue by mauriciogracia** [neomjs/neo#2889]
While looking around https://neomjs.github.io/pages/node_modules/neo.mjs/dist/production/examples/component/coronaHelix/index.html and using the FollowSelection option 

when I move the arrow, the selection moves to next/previous card and then the cards are scrolled and seems like two changes when is not the case

An intermediate animation of the cards when scrolling will make the change/animation more smooth, without the selection jumping from one card to the other.

**Comment by tobiu** [comment]
deployed the change to the online examples. enjoy.
