### ISSUE TITLE
Drag&drop broken inside chrome for windows

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#3146]
we encountered this on @davhm laptop recently. it affects moving and resizing dialogs as well as calendar events.

it would be nice if another windows-user could double-check this to ensure it is not just a local setting causing trouble (on windows on my machine).

a bit weird for sure that chrome acts differently on MacOS.

**Comment by davhm** [comment]
This seems to have been a one-off, since drag & drop is working fine again (I've just tested it). Probably caused by some broken state being loaded.

I vote for closing.

**Comment by tobiu** [comment]
closing sounds good. it might have been related to: https://github.com/neomjs/neo/issues/3267
