### ISSUE TITLE
buildScripts/createClass

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#3176]
I want to create a convenience CLI program, which simplifies creating new neo classes.

For the start, you should be able to pick between a base class of `component.Base` and `container.Base`.

There will be follow-up tickets, like extending view models and controllers.

**Comment by davhm** [comment]
This sounds like a very valuable improvement! I also love the iterative approach thinking in small increments 👏

**Comment by tobiu** [comment]
<img width="1105" alt="Screenshot 2022-06-21 at 23 01 23" src="https://user-images.githubusercontent.com/1177434/174896799-558c6af1-38c8-4971-a9cf-c20ca99c6741.png">

getting closer :)

**Comment by tobiu** [comment]
<img width="862" alt="Screenshot 2022-06-21 at 23 47 59" src="https://user-images.githubusercontent.com/1177434/174902782-f9265645-9650-4a46-939a-442a4eea2af0.png">

**Comment by tobiu** [comment]
created a decent state for the first version, more extensions will follow inside new tickets.
