### ISSUE TITLE
form.field.Text: styling for invalid values

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#3201]
currently, form.fields are using a DOM level based pseudo selector to mark the validity.

this needs to change, e.g. in case we create a form for creating a new entity, we most likely want the fields to look "clean" => no "red borders" (error indicators).

as a first step, we should remove the DOM based selector rules and use the neo `neo-invalid` rule instead.

this will apply a border on the wrapperEl in case this exists => same level as the active border.

for now, i think the active state should have a prio compared to errors (a bit like validate on blur), but this could be optional (follow up ticket).

**Comment by davhm** [comment]
Wouldn't this mean that if a focused field's value is changed to an invalid state, the user won't see any validation errors until he has **un**focused the field? IMO error state should be more important than active state. E.g. see how Material does it:

A required and validated field just after focus and during input:
![image](https://user-images.githubusercontent.com/105657166/175902337-007589f6-71e1-4912-9ab4-ec5b6debffe6.png)

The same field after a blur event:
![image](https://user-images.githubusercontent.com/105657166/175902592-04a9dd94-0fa1-474c-bae6-09b06a06c391.png)
