### ISSUE TITLE
Update the Documentation - Main Area Update

### ISSUE THREAD

**Issue by Dinkh** [neomjs/neo#3238]
**Is your feature request related to a problem? Please describe.**
I would prefer to have the information sorted in a different way.

![Demo Image](https://www.imgbly.com/ib/9IfnbtTdet)
https://www.imgbly.com/ib/9IfnbtTdet

**Describe the solution you'd like**
Take a look at the image to see a possible solution

**Comment by tobiu** [comment]
where / how would you display the info if something is private or static?

**Comment by Dinkh** [comment]
We could add a colored badge for these right after config:type
