### ISSUE TITLE
Update Documentation - 3 Tabs instead of one - Demo Apps and User Apps and API

### ISSUE THREAD

**Issue by Dinkh** [neomjs/neo#3239]
Demo Apps (e.g. Helix) should not be part of the ´API´ documentation, but be added to ´Examples´.

The user Apps should be inside a tab ´Apps´.

Currently all Apps are part of the API documentation

**Comment by tobiu** [comment]
be careful with mentioning examples in this context. right now the structure of the 3 tabs is:

1. API
2. Tutorials
3. Examples (demo apps loaded into the docs app)

so, we could split the first tab into API src and API apps.

inside the framework docs, we do show all apps (API) of the framework (until we adjust the GitHub pages to be able to pull them in from different repos).

inside the workspace docs, we do show all self created apps (API).

Adding the API of examples is possible (new ticket though).

**Comment by Dinkh** [comment]
Is it possible to remove the Demo Apps from the Workspace build process, so that we get a clean setup?
I like the idea of having these example (Helix...) but I would prefer not to build them in my professional setting.

**Comment by tobiu** [comment]
workspace build process: node_modules should be excluded from split chunks. at least on MacOS this is the case. you can easily verify if it is the same on windows with searching for demo app class names inside `dist/production/chunks/app`.

the docs app parser `buildScripts/docs/jsdocx.mjs` will include the apps for the neo and workspace scope. removing framework apps for this scope is definitely possible (new ticket please).
