### ISSUE TITLE
buildScripts/createClass: import paths inside the workspace scope

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#3259]
framework related base class imports are missing the `node_modules/neo.mjs/src` part.

will take a look into this.

**Comment by tobiu** [comment]
```
const
      __dirname   = fileURLToPath(new URL('../', import.meta.url)),
      cwd         = process.cwd(),
      requireJson = path => JSON.parse(fs.readFileSync((path))),
      packageJson = requireJson(path.join(__dirname, 'package.json')),
      insideNeo   = packageJson.name === 'neo.mjs',
```

we had `__dirname = path.resolve()` before and this explains, why insideNeo now always true which collides with the import paths.

@ThorstenSuckow I guess the change is required for the drop logic, but we need a way to "unbreak" the default mode. i will create a workaround, but it would be appreciated if you could double-check it as well.

**Comment by tobiu** [comment]
I kept the packageJson variable as it is, but adjusted the framework check:
`insideNeo = process.env.npm_package_name === 'neo.mjs',`

this should not affect the drop mode.

**Comment by ThorstenSuckow** [comment]
We should probably add more test cases for this in the future. Is the `insideNeo` an indicator for the location from which the script was executed?

**Comment by tobiu** [comment]
correct. as long as you don't use the name `neo.mjs` as the package name of your workspace, it is a safe bet.
