### ISSUE TITLE
Multi-window scope: adding support for re-opening an app

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#3269]
Inside e.g. the shared covid dashboard, we can expand views like the helix into new browser windows.

this does work fine for the first opening => we get a new app name and the theme map will store flags for added css files (delta updates). closing the helix and displaying it correctly works as well, since the original window already contains the required css.

however, in case we expand the helix into a new window again (using the same app name), the css won't get added, since the flags inside the map are already set.

we need a new algorithm to remove an app from the theme map and we should trigger it when destroying an app (inside the shared workers context).

**Comment by tobiu** [comment]
@Dinkh

**Comment by Dinkh** [comment]
Same for my app.
👍

**Comment by tobiu** [comment]
i would actually stick to enhancement, but it depends on the definition.
1. bug: an implemented feature does not work as expected
2. enhancement: a feature is not implemented yet

gray zone for this one i guess :)

**Comment by Dinkh** [comment]
Enhancement: Now you can even reopen a window
Bug: I expect to even reopen the window

I would tend to bug, but from the naming of the ticket it is an enhancement ;)

**Comment by tobiu** [comment]
the "bug-feature" is resolved now. enjoy.
