### ISSUE TITLE
Neo.data.Model should be renamed to something else, such as Neo.data.Record

### ISSUE THREAD

**Issue by maxrahder** [neomjs/neo#3625]
"Model" is a highly overloaded term in programming, and even within Neo it can refer to a "view model" or a record class. When I talk to developers or in training, I always avoid using the term "model" since the audience may have preconceptions about what it means. Therefore, in Neo we need a different term. I suggest `Neo.data.Record`. 

I do realize that a "record" is an instance, and stores are collections of records. But it's in OOP it's common for the instance to reflect the name of its class. For example, one defines a `Neo.data.Store`, and the instance is called a "store". There are numerous similar examples. I'd be tempted to call the record class `Neo.data.Entity`, as in "entity-relationship" (database) modeling, but "entity" is pretty ambigious too. I can't think of a better name than `Ext.data.Record`.

**Comment by tobiu** [comment]
sounds like a discussion item for @ThorstenSuckow @ExtAnimal.

I do agree, that "model" for data & component models does sound a bit confusing.

However, records in neo are **not** model instances, but slightly enhanced objects (we need change events).

There is a `Neo.data.RecordFactory` in place, which would also create confusing with a record based naming.

Maybe `Neo.data.Entity` could work.

The bigger naming issue I see is that Angular & React devs got used to call a view model / state provider `Store`. In our world we automatically think of `data.Store`.

Open for ideas, in case we can make our namings easier. Needs to be bullet-proof :)

**Comment by Dinkh** [comment]
I am fine with model, as it is only a model-description.
Record would be the rendered data, based on the model-description.

For me there is no need to rename it.
