### ISSUE TITLE
Button Types: Primary, Secondary, Tertiary

### ISSUE THREAD

**Issue by mxmrtns** [neomjs/neo#3652]

**Comment by Dinkh** [comment]
I would like to have the definition as ui.

@example:
```
{
    ntype: 'button',
    ui: 'primary'
}
```

This creates automatically a cls
=> neo-button-primary

**Comment by Dinkh** [comment]
Currently added as Pull-Request the programming part.

Still someone has to add css classes:

neo-button-primary
neo-button-secondary
neo-button-tertiary
