### ISSUE TITLE
container.Base: createItem() => removes default values

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#3746]
the check if an item has a module => removing the ntype and vice versa is getting applied to the itemDefaults object, so it will affect all following items.

we need to change this behavior to only change a shallow copy.

@Dinkh: this explains why window actions not always show up. the toolbar spacer is a `module: Component`, removes the default button ntype, actions become components and the styling is lost.

**Comment by Dinkh** [comment]
lets add baseCls with this ticket.
