### ISSUE TITLE
Themes should optionally only need colors

### ISSUE THREAD

**Issue by Dinkh** [neomjs/neo#3781]
I would like to be able to only add a style.scss with colors being merged with light and dark.
To be able to use it, there should be a preset file.

Whatever item you leave blank, will be taken from the parent-theme.

style.scss
```
    'base-theme': 'theme-light',

    'button-active-background-color'  : #ddd,
    'button-active-border-color'    : #1c60a0,
    'button-active-color'             : #1c60a0,
    'button-background-color'         : #fff,
    'button-background-image'         : none,
    'button-background-gradient-end'  : #323536,
    'button-background-gradient-start': #434749,
    'button-badge-background-color'   : #1c60a0,
    'button-badge-color'              : #fff,
    'button-badge-margin-left'        : -10px,
    'button-badge-margin-top'         : -10px,
   ...
```

**Comment by tobiu** [comment]
a theme in general is just a "vars" folder. merging a theme with a base theme is tricky (not impossible though). we would need to enhance the build and watch themes engine.

the more important item is imho adding color palettes to themes and using most other variables by reference (e.g. adjusted with `darken()` or `lighten()`. might be a topic for @mxmrtns.
