### ISSUE TITLE
Container needs a getReference() method

### ISSUE THREAD

**Issue by maxrahder** [neomjs/neo#3799]
Simple container views may not need a controller, and may still need to get references to child items. For consistency, the component should be able to look up components via their "reference" just like their controller can.

There is a `this.down({})` method, but strangely, that doesn't work for child items that have a "refence" config. This.down using the "reference" property should also work.

**Comment by tobiu** [comment]
hi max,

make sure you don't have any typos in there (you wrote "refence"). it definitely does work, otherwise references would not.

https://github.com/neomjs/neo/blob/dev/src/controller/Component.mjs#L116

```
    getReference(name) {
        let me        = this,
            component = me.references[name];

        if (!component) {
            component = me.component.down({reference: name});

            if (component) {
                me.references[name] = component;
            }
        }

        return component || null;
    }
```

closing the ticket. if you find a breaking use case, we can re-open it :)
