### ISSUE TITLE
Add option for select field to prevent free text input 

### ISSUE THREAD

**Issue by mxmrtns** [neomjs/neo#3874]
There are use cases where the user should not be able to type free text into a select field.

Clicking anywhere on the select field will trigger the popover menu with the option list.

The cursor shall be 'pointer' while hovering anywhere over the select field

**Comment by tobiu** [comment]
hi max, should be the same one as: https://github.com/neomjs/neo/issues/3806

**Comment by mxmrtns** [comment]
[Example](https://nordhealth.design/components/select/examples/basic/)

**Comment by tobiu** [comment]
let's close this one and make the other one a priority.
