### ISSUE TITLE
button.Base: UI variations

### ISSUE THREAD

**Issue by mxmrtns** [neomjs/neo#3998]
Following up on #3996 

In order to cater for different UI needs, I suggest splitting up the CSS variables for buttons into 'Base'(values that should be the same across all different button types) and 'UI Variants' like Primary or Secondary.

### Base
- border-radius
- font-family
- font-size
- button-outline-focus
- [...] anything that should stay the same across the different UI button types
### Primary
- button-secondary-background-color
- button-secondary-text-color
- button-secondary-border-color
- [...] anything that should be changeable for each UI variation
##### :hover
- button-secondary-background-color-hover
- button-secondary-text-color-hover
- button-secondary-border-colour-hover
##### :active
- button-secondary-background-color-active
- button-secondary-text-color-active
- button-secondary-border-color-active
##### Disabled
- button-secondary-background-color-disabled
- button-secondary-text-color-active-disabled
- button-secondary-border-color-active-disabled

--- 

The same variable structure would be needed for the following UI button types:

- Secondary
- Tertiary
- Ghost

**Comment by tobiu** [comment]
Hi Max,

this took quite a while. Let us create a follow up ticket for the ghost ui.

we most likely also need `pressed` states for our different button uis:
https://m2.material.io/design/interaction/states.html#usage

also a follow up ticket if needed. Let's do a quick call tomorrow.
