### ISSUE TITLE
button.Base: UIs and variables

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#4057]
@mxmrtns @Dinkh @deniztoprak @maxrahder 

we do have 4 UIs in place now, but the styling (the values) do not match the specs yet. i also think that we can most likely reduce the amount of variables quite a bit.

assuming that i understood max (m) correctly, let us take a quick look into the different UIs inside the github platform.

primary:
<img width="163" alt="Screenshot 2023-02-15 at 11 48 01" src="https://user-images.githubusercontent.com/1177434/219015544-160d1e0c-8610-4d09-a188-018cc7533d7c.png">

secondary: (mostly used inside neo so far)
<img width="138" alt="Screenshot 2023-02-15 at 12 30 03" src="https://user-images.githubusercontent.com/1177434/219015746-db3f7590-a7ef-40bd-abd8-ec7e087279d5.png">

tertiary: (just looking like a link, no effects)
<img width="121" alt="Screenshot 2023-02-15 at 12 30 21" src="https://user-images.githubusercontent.com/1177434/219016008-a4fd3235-01df-45d2-9b54-ea6095da12fc.png">

ghost: (looks like text, but gets a background effect or border on hover, pressed, focus)
<img width="303" alt="Screenshot 2023-02-15 at 12 30 16" src="https://user-images.githubusercontent.com/1177434/219015816-c399995d-8757-4119-aab2-8bd738376b28.png">

@mxmrtns is this correct?

**Comment by mxmrtns** [comment]
@tobiu Yes, thats correct!
