### ISSUE TITLE
new variables for table

### ISSUE THREAD

**Issue by MRHajari** [neomjs/neo#4060]
These variables are missing in the theme table-->header-->button.scss. please add those.
 'tab-button-gap' 
  'tab-button-height'  
  'tab-button-width'  
  'tab-button-padding'  

 These variables are missing in the theme table-->Container.scss. please add those.
  'table-container-cell-border-bottom'   
   'table-container-cell-padding'       
   'table-container-cell-height' 
   'table-container-cell-gap'

**Comment by tobiu** [comment]
added the table vars except for gap. this one is rather complex and imho not needed.
