### ISSUE TITLE
button.Menu

### ISSUE THREAD

**Issue by MRHajari** [neomjs/neo#4062]
I need this button.Menu, which can be seen in the image.

<img width="396" alt="Bildschirm­foto 2023-02-15 um 15 13 04" src="https://user-images.githubusercontent.com/86204452/219075883-abc671ff-9b6e-4f59-abc3-0c65ed4bdb6f.png">

**Comment by tobiu** [comment]
we already have the base class:
https://github.com/neomjs/neo/blob/dev/src/button/Menu.mjs

and we actually have 2 different list implementations:
https://github.com/neomjs/neo/blob/dev/src/menu/List.mjs
https://github.com/neomjs/neo/blob/dev/src/menu/Panel.mjs

so we need to "just" connect them.

menu online demo:
https://neomjs.github.io/pages/node_modules/neo.mjs/examples/menu/panel/

<img width="421" alt="Screenshot 2023-02-15 at 16 47 31" src="https://user-images.githubusercontent.com/1177434/219078480-d2b82044-c2d9-4ae3-b4db-aa0a56f14a15.png">

keyNav is already in there.
