### ISSUE TITLE
form.field.Checkbox: Required validation needed

### ISSUE THREAD

**Issue by alberthashani** [neomjs/neo#4161]

**Comment by tobiu** [comment]
some thoughts: we could pretty easily add a `required_` config, as well as a `validate()` & `isValid()` method. these methods could add a `neo-invalid` css rule and we could e.g. add a red color.

adding an error message (label) would be a follow up ticket which requires more work => we would need to adjust the vdom structure to support it.

**Comment by alberthashani** [comment]
Nice, I think we would need the custom error message right away, so shall i include/define that in the description of this feature request or is it nessecary from your point of view to have them in sperate feature requests?

**Comment by alberthashani** [comment]
Ok I’m with you, i will create anither ticket for custom error messages as soon as this is closed.

**Comment by tobiu** [comment]
done now. let us create a new ticket for `groupRequired` or similar (check 1+ items out of many)
