### ISSUE TITLE
enabling/disabling "e" notation for numeric Inputs

### ISSUE THREAD

**Issue by StefanKleiner101** [neomjs/neo#4266]
The "e" Notation for Numeric Inputs is not an expected behaviour outside of scientific fields where big numbers are used a lot and the input of an "e" as a default for normal inputs is in some cases (for example for the input of Percent-Values) not even valid.

Therefore there should be an option to either enabling the "e"-Notation or disabling it (in case it should be an default-option).

When disabled, the input should surpress the "e"-Keystroke just like any other letter/character that is not an Number.

**Comment by tobiu** [comment]
resolved by https://github.com/neomjs/neo/issues/4416
