### ISSUE TITLE
field.Select: When clicking on the SelectField area other than the icon, the selectList/picker shows only the 1 item that is selected

### ISSUE THREAD

**Issue by alberthashani** [neomjs/neo#4269]
**Describe the bug**
field.Select: When clicking on the Select area other than the icon, the selectList/picker shows only the 1 item that is selected.

**To Reproduce**
1. Select one random item of a SelectField
2. After selecting, Click on SelectField (not the icon, for example in the middle of the field) 
3. The Picker should now show only the 1 selected item

Config of the select field:
{
    module: Select,
    cls: [ 'col-10-13'],
    placeholderText: 'Sort...',
    clearable: false,
    hideLabel: true,
    showOptionalText: false,
    required: false,
    editable: false,
    value: Neo.sortSelectedValue ? Neo.sortSelectedValue : null,
    listeners: {
        select: 'onSortFieldSelect'
    },
    store: {
        data: [
            { id: '1', name: 'A-Z' },
            { id: '2', name: 'Z-A' }
        ]
    }
}

**Comment by tobiu** [comment]
@alberthashani it took me quite a while, but i can reproduce it now. the issue happens in case we programatically set a value for the field.
