### ISSUE TITLE
form.field.CheckBox: labelPosition : 'top' has broken alignment

### ISSUE THREAD

**Issue by rushikesh-wasule** [neomjs/neo#4369]
Checkbox label alignment breaks after this change : [https://github.com/neomjs/neo/commit/02b703ce97bfb7ac73099cce94a8a2f2519a5606](url)

**Comment by tobiu** [comment]
needs more work. we now have 2x a label element (top level VS title lable).

**Comment by tobiu** [comment]
let's see if this approach works.
