### ISSUE TITLE
form.field.Phone: inputPattern edge cases

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#4386]
@ki1pen @deniztoprak 

the new inputPattern regex does not support the following format:
`+49 (151) 1234 567`

so we should polish it more. open for ideas :)

**Comment by deniztoprak** [comment]
It's hard to find one-size-fits-all pattern to validate tel inputs. There are some good insights here:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel#validation

There are people arguing that phone number validation is useless:

https://stackoverflow.com/questions/14639973/javascript-regex-what-to-use-to-validate-a-phone-number/21117154#21117154

And some specialized libraries which can inspire:

https://github.com/google/libphonenumber
