### ISSUE TITLE
Cypress configuration into Neo

### ISSUE THREAD

**Issue by subramaniyamP** [neomjs/neo#4487]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
in configuration of neo framework for component testing in cypress. we need to integrate cypress with our neo app.

**Describe alternatives you've considered**
Able to run E2E but component testing in cypress.

**Additional context**

**Comment by tobiu** [comment]
cross reference ticket: https://github.com/cypress-io/cypress/issues/27002
