### ISSUE TITLE
Make border !important

### ISSUE THREAD

**Issue by mxmrtns** [neomjs/neo#4511]
https://github.com/neomjs/neo/blob/63bc6a6a00b069733f11c69645b5b0d17000ff83/resources/scss/src/button/Base.scss#LL159C3-L159C3

The border property from the ghost button is currently overwritten by the border from .neo-button:active

**Comment by mxmrtns** [comment]
@tobiu This is till an issue for every button style that does not want to use a border (in my case tertiary and ghost). 

Is it possible to remove the "!important" from the[ default active state](https://github.com/neomjs/neo/blob/63bc6a6a00b069733f11c69645b5b0d17000ff83/resources/scss/src/button/Base.scss#L103)? 


`    &:active {
border : v(button-border-active) !important;
`
change to → 
`    &:active {
border : v(button-border-active) ;
`

**Comment by tobiu** [comment]
hi max! this ticket fell under the radar :)

i think the `!important` was intended to give the active boder a prio over error css (e.g. a red border). need to double-check if we can remove it without breaking this order.

however, you are right: only the primary ui has the important flag, all others don't. so we could also just add the flag into the other uis and should be good.

**Comment by tobiu** [comment]
let's try, if this quick-fix already does the trick. if not, we can re-open the issue.
