### ISSUE TITLE
Neo.component.Menu: A Menu component to display a list of choices on a temporary surface

### ISSUE THREAD

**Issue by alberthashani** [neomjs/neo#4512]
It should display a list of choices on a temporary surface.

**Comment by tobiu** [comment]
what would be the difference to `menu.List` or `menu.Panel`?

**Comment by alberthashani** [comment]
So neo already has menu components, have to look them up, and let you know if that's what is needed.

**Comment by alberthashani** [comment]
menu.List is pretty much what is needed, I will close this request as soon as we manage to integrate it.
