### ISSUE TITLE
component.Video: cleanup

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#4552]
hi torsten,

a couple of thoughts:

1) in case you are not using the vdom reference, don't assign it to a variable. we can use `this.update()` instead of `this.vdom = vdom`. already changed in all other spots inside the framework.
example: https://github.com/neomjs/neo/blob/dev/src/button/Base.mjs#L169

2) same pattern for domListeners => `this.addDomListeners()`
example: https://github.com/neomjs/neo/blob/dev/src/button/Base.mjs#L181

3) the `playing_` config defaults to false. on DOM level there is `autoplay: true` though. i guess autoPlay could be a config on its own.

please drop a comment in case you want me to add the changes.

**Comment by Dinkh** [comment]
autoplay is used to immediately start playing the video, when you click the ghost.
I will add a autoplay functionality anyways.

**Comment by Dinkh** [comment]
fixed and added autoplay
