### ISSUE TITLE
form.field.Select editable config not working

### ISSUE THREAD

**Issue by pensuwan-k** [neomjs/neo#4555]
I use module form.field.Select with editable: false. But the input can still be edit.

**Comment by tobiu** [comment]
hi kiattipoom!

i already took a quick look last friday:
<img width="2120" alt="Screenshot 2023-07-24 at 09 29 06" src="https://github.com/neomjs/neo/assets/1177434/dfd77cb6-5dde-4fba-bd88-09528ec39eeb">

`pointer-events: none` as well as `user-select: none` do still get applied.

however, the field does receive focus. maybe being set programmatically? definitely a regression bug.
