### ISSUE TITLE
add "icon", "label", "anchorPoint" fields, etc to Neo.main.addon.GoogleMaps.addMarker(data)

### ISSUE THREAD

**Issue by gplanansky** [neomjs/neo#4595]
**The GoogleMaps legacy marker implements fields beyond the "title" and "position".**
https://developers.google.com/maps/documentation/javascript/reference/marker#MarkerOptions

The icon, label fields are useful.
(Neo examples/component/wrapper/GoogleMaps/ MapComponent.mjs already codes icons, but addon omits them.)

line 95 ff src/main/addon/GoogleMaps.mjs
 ```
  position: data.position,
  title       : data.title,
  icon       : data.icon,  // add these
  label      : data.label,    
  etc. 

```

**Comment by tobiu** [comment]
added the 3
