### ISSUE TITLE
Variables for popover menu

### ISSUE THREAD

**Issue by mxmrtns** [neomjs/neo#4612]
For styling this component, we would need the following variables.

**Menu Item**
- height

- padding

- gap (something to control the distance between the icons and text)

- font-familiy, color, font-weight, line-height, text-transform

- font-color and icon color for disabled state

- background-color
- background-color-hover
- background-color-pressed
- background-color-disabled

-outlined-focused

**Comment by tobiu** [comment]
i guess i should have mentioned that `menu.List` is extending `list.Base` which already has some of them :)

well, unless we do want different styling for lists when they are inside floating containers.

**Comment by tobiu** [comment]
added around half of them. let's connect tomorrow to figure out, if modifying `list.Base` instead is smarter.

**Comment by tobiu** [comment]
i assume that "pressed" should mean "selected". unless you want a ripple effect or a different state onMouseDown (which is different to the selected look and vanishes onMouseUp).

**Comment by tobiu** [comment]
i think i got them all now.
