### ISSUE TITLE
ES2020: Add optional chaining once possible (Webpack issue)

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#467]
In short:

```
const obj = {
  prop1: {
    prop2: {
      prop3: {
        prop4: {
          prop5: 5
        }
      }
    }
  }
}

obj.prop1 &&
  obj.prop1.prop2 &&
  obj.prop1.prop2 &&
  obj.prop1.prop2.prop3 &&
  obj.prop1.prop2.prop3.prop4 &&
  console.log(obj.prop1.prop2.prop3.prop4.prop5);
```

VS

```
const obj = {
  prop1: {
    prop2: {
      prop3: {
        prop4: {
          prop5: 5
        }
      }
    }
  }
}

console.log(obj?.prop1?.prop2?.prop3?.prop4?.prop5);
```

This can some boiler-plate code, but unfortunately, webpack can not handle it yet. Browsers already support it, but webpack wants to parse it.

> ERROR in ./apps/covid/view/TableContainerController.mjs 191:37
> Module parse failed: Unexpected token (191:37)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |         }
> | 
> >         me.loadHistoricalData(record?.countryInfo?.iso2 || 'all');

Since Babel is not an option for neo, we need to wait for this PR:

https://github.com/acornjs/acorn/pull/891

(Webpack relies on acornjs)

**Comment by tobiu** [comment]
https://caniuse.com/#search=optional%20chaining

**Comment by dreyks** [comment]
https://github.com/acornjs/acorn/pull/891 is merged, let's keep an eye on the releases

**Comment by tobiu** [comment]
Thanks for the heads up!

There are probably many spots inside the neo.mjs framework & demo apps code base where we can use it. Optional chaining can definitely help removing some boiler plate code (smaller file-size) as well as making the spots cleaner & easier to read.

Looking forward to it.

**Comment by tobiu** [comment]
just double-checked this one again and we are now finally good to use optional chaining.

will create new tickets in case i see spots.
