### ISSUE TITLE
Add DACH country codes for post code validation

### ISSUE THREAD

**Issue by r-l-d** [neomjs/neo#4697]
**Is your feature request related to a problem? Please describe.**
I need to validate DACH postal codes. Currently, in the src>form>field>ZipCode.mjs file, only DE is listed in the countryCodes opbject.

**Describe the solution you'd like**
I would like AT and CH added to the countryCodes object to validate their postal codes:

`static countryCodes = {
        DE: /^(?!01000|99999)(0[1-9]\d{3}|[1-9]\d{4})$/,
        AT: /^\d{4}$/,
        CH: /^\d{4}$/
    }`

**Describe alternatives you've considered**
Perhaps it is possible to do this with the Overwrites file instead? I'm not sure, since the countryCodes object is not part of the ZipCode config.

**Additional context**

**Comment by tobiu** [comment]
hi ross, you are very welcome to send a pull request :)

ping me in case you have questions on how that works (creating a fork).

**Comment by r-l-d** [comment]
Thanks @tobiu, I've created a PR here: https://github.com/neomjs/neo/pull/4699

**Comment by tobiu** [comment]
thx! just cleaned up the formatting.
