### ISSUE TITLE
util.Logger: logError() is not able to properly parse specific scenarios

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#4709]
I added `console.log(args)` into `logError()` to see the given input.

![Screenshot 2023-08-14 at 13 39 14](https://github.com/neomjs/neo/assets/1177434/9a156abc-8720-4556-9678-a65ce35a2fa9)

**Comment by tobiu** [comment]
to reproduce this one, you can just add the following into any cmp, assuming a view controller exists somewhere:
```
domListeners: {
    click: 'notExistingFn'
}
```

**Comment by Dinkh** [comment]
Tested in portal app, by adding the example.
Fixed
