### ISSUE TITLE
form.field.Switch: styling doesn't apply

### ISSUE THREAD

**Issue by pensuwan-k** [neomjs/neo#4724]
the base class in form.field.Switch does not match with the class in scss file

**Comment by tobiu** [comment]
do you want to add a PR? should be just the missing `neo-` inside the scss file.

i will create a new ticket for the missing example app.

tagging torsten @Dinkh

**Comment by tobiu** [comment]
<img width="744" alt="Screenshot 2023-08-15 at 17 18 58" src="https://github.com/neomjs/neo/assets/1177434/d7d7b88a-18ed-4598-8ec5-62d211959cf0">

looks pretty much the same in both themes
