### ISSUE TITLE
tab.header.Toolbar: sortable

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#4767]
just noticed that inside the docs app, sorting only works fine for the first time you do it.

afterwards the tab header toolbar still has a `height` of 25px, but it gets displayed with 1px instead.

tested using a min-height and this worked. needs further investigation.

**Comment by prathammpurohit** [comment]
Hey @tobiu, I would like to work on this issue. May we discuss this issue in detail?

Can you attach a screenshot of the concern?

**Comment by tobiu** [comment]
hi @prathammpurohit,

unfortunately this one is not a good ticket for getting started with neo. @ExtAnimal is in the middle of adding support for smart positioned floating components. I just noticed that there is a side effect when converting rect objects into DOMRects inside the app worker. i will create a new ticket for it, since it is blocking this one.

my recommendation, in case you want to help out a bit, is to join the neo slack channel and get connected.

best regards,
tobias
