### ISSUE TITLE
Neo.tree.Accordion: Throwing jsdocx errors on build, on line 40 and 51

### ISSUE THREAD

**Issue by alberthashani** [neomjs/neo#4795]
Errors:

repoX@0.1.0 generate-docs-json
node ./node_modules/neo.mjs/buildScripts/docs/jsdocx.mjs

Start default jsdocx parsing.
Error: ERROR: Unable to parse a tag's type expression for source file /Users/username/repos/repoX/node_modules/neo.mjs/src/tree/Accordion.mjs in line 40 with tag title "member" and text "{Record[|null} selection=null": Invalid type expression "Record[|null": Expected "!", "#", "$", "(", "-", ".", "/", "0", ":", "<", "=", "?", "@", "[]", "\\", "_", "|", "~", "‌", "‍", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter, [1-9], or end of input but "[" found.
ERROR: Unable to parse a tag's type expression for source file /Users/username/repos/repoX/node_modules/neo.mjs/src/tree/Accordion.mjs in line 51 with tag title "member" and text "{Record[|null} selection=null": Invalid type expression "Record[|null": Expected "!", "#", "$", "(", "-", ".", "/", "0", ":", "<", "=", "?", "@", "[]", "\\", "_", "|", "~", "‌", "‍", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter, [1-9], or end of input but "[" found.

**Comment by tobiu** [comment]
Torsten, magst du da mal schauen?

Meine Vermutung: `@member {Record[|null} selection=null`

=> Record ist kein in JS bekannter Type, und es müsste dann wohl `{Object[]|null}` sein. gleiches gilt auch bei den methods.

**Comment by tobiu** [comment]
alright, i will take care of this one then.

**Comment by tobiu** [comment]
@alberthashani: the docs build works again.
