### ISSUE TITLE
form.field.Checkbox, form.field.Text: Fire userChange event

### ISSUE THREAD

**Issue by pensuwan-k** [neomjs/neo#4818]
It would be good to make a distinction between change events that are triggered programmatically or by user input

**Comment by dztoprak** [comment]
@tobiu  I tried to implement `userchange` event in Checkbox component's `onInputValueChange` method:

https://github.com/neomjs/neo/blob/8533de4ad4f96cda296b28858db3a54cbe0b7e96/src/form/field/CheckBox.mjs#L493-L501

But this method also gets triggered when the checkbox value is changed programmatically (e.g. bind). Is there any other way to differentiate user triggered change?

**Comment by tobiu** [comment]
you are right: a programmatic change will trigger `onInputValueChange ()` too, since it will update the DOM afterwards.

however: inside the method => if `checked === me.checked` it should be a programmatic change (since the value already updated before the DOM change) and vise versa. just thinking out loud, needs some testing :)

**Comment by dztoprak** [comment]
Just tested the solution:

https://github.com/dztoprak/neo/blob/de72ed5b0a4aa39c0ec06f5b8358fbb0dd564915/src/form/field/CheckBox.mjs#L493-L505

`checked` has always the opposite value of `me.checked`, so the condition is never true.

**Comment by shrutiambekar** [comment]
@ThorstenRaab

**Comment by tobiu** [comment]
<img width="808" alt="Screenshot 2023-09-10 at 23 22 29" src="https://github.com/neomjs/neo/assets/1177434/804ffc42-ab9e-4c25-bb47-2e0ab7a127dc">

@dztoprak: just did a quick test. the first 2 changes happened when clicking on the field. opposite value for this one.

when programmatically changing the checked state, `onInputValueChange()` does not trigger at all for me. so we could just always fire a custom event in there. needs testing :)

**Comment by tobiu** [comment]
looks the same way for TextFields:
<img width="814" alt="Screenshot 2023-09-10 at 23 27 59" src="https://github.com/neomjs/neo/assets/1177434/19dc19c7-75e7-42ed-8cb1-0039c4821628">

**Comment by dztoprak** [comment]
For me, the `onInputValueChange` is triggered by all programmatic changes in checkboxes. I haven't tried with the text fields though:


https://github.com/neomjs/neo/assets/126246513/902d9a2b-dd98-41f0-a8fa-a5ebedadf3c7

**Comment by tobiu** [comment]
careful deniz: IF you are clicking on one checkbox to change the checked state of a different one, you will get onInputValueChanged() for the one you clicked on :)

try what i did => control + right click on a checkbox. store it inside a global var. then change the checked state inside the dev tools.

**Comment by dztoprak** [comment]
good point, checkbox controllers are not exempt from the checkbox logic of course 😄

**Comment by dztoprak** [comment]
@tobiu do you know how can I access the `oldValue` in Text's `onInputValueChange` method?

**Comment by tobiu** [comment]
sure. before setting this.value, you can access `this.value` or `this._value` to get the old value :)
