### ISSUE TITLE
Neo.tree.Accordion: onStoreRecordChange doesn't change icon

### ISSUE THREAD

**Issue by dztoprak** [neomjs/neo#4836]
In `Neo.tree.Accordion` component:
 
`itemVdom = VDomUtil.getByFlag(vdom, field.name);`

doesn't find the vdom because the flag is named incorrectly. Instead of `flag: "icon"`, it should be `flag: "iconCls"`;

**Comment by tobiu** [comment]
do you want to send a PR or should @Dinkh look into it?

**Comment by dztoprak** [comment]
@pensuwan-k has done the change, will open the PR in a while.
