### ISSUE TITLE
tree.Accordion: more than one iconCls in store break when update

### ISSUE THREAD

**Issue by pensuwan-k** [neomjs/neo#4855]
When create the accordion item with more than one class in iconCls ('icon1' -> work) ('icon1 icon2'-> doesn't work)
And the update the iconCls in the store it's break with this error.

![Screenshot 2023-09-06 at 16 24 11](https://github.com/neomjs/neo/assets/126779879/2128e3e5-5b86-48e4-9681-b11bc4204a08)

**Comment by tobiu** [comment]
@Dinkh can you take care about this one? i suggest using an array of strings for `iconCls` and just spread it in. would be consistent then to other implementations.

**Comment by Dinkh** [comment]
Fixed
