### ISSUE TITLE
dialog.Base: maximise is no longer animated

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5008]
regression issue.

before removing the wrapper, we had the following CSS rule(s):
https://github.com/neomjs/neo/blob/7c7d3bd794ab3f00845de69645dc0214feee4fab/resources/scss/src/dialog/Base.scss#L25

to do it in a good way, the dialog should get a new config called `animate_`.

`animateTargetId` is still needed for spawn animations, but a more generic config to enable / disable all animations seems reasonable.

`afterSetAnimate()`should add a new top level CSS rule like `neo-animated` which should contain similar rules to the old wrapper CSS.

**Comment by ExtAnimal** [comment]
`animate` is too broad a name. This is to affect only whether maximize animates or not?

I suggest making `maximizable` a potentially granular config eg:

`maximizable : true/false` to enable and disable maximizing (and control the visibility of the button) in the basic case.

and

```
maximizable : {
    animate : true
}
```

It's a truthy value, so it is maximizable. And it describe *how* to maximize.

This concept van be applied to many configs whose modes of operation is spread among several related configs.

**Comment by tobiu** [comment]
bug already fixed.

the maximise button is controlled via a header action. feel free to open a follow up ticket, in case we want to be able to maximise without an animation.
