### ISSUE TITLE
tree.Accordion: Selection model in tree.Accordion doesn't work

### ISSUE THREAD

**Issue by pensuwan-k** [neomjs/neo#5036]
The styling of the selected record doesn't get applied after the data for the tree.Accordion get updated.
It crashes in card layout context. The selection applied, get kick out of DOM, drop it back in, lost.

**Comment by tobiu** [comment]
hi @pensuwan-k,

i added a "Remove DOM" button into the example:
<img width="1424" alt="Screenshot 2023-10-19 at 13 04 03" src="https://github.com/neomjs/neo/assets/1177434/acbd3915-2996-4048-b583-d9c43daf0530">

<img width="1430" alt="Screenshot 2023-10-19 at 13 04 20" src="https://github.com/neomjs/neo/assets/1177434/15e47702-a720-4297-937c-d2059b052840">

When I drop the DOM back in, the selection is still in place. We need a reproducible testcase.

**Comment by pensuwan-k** [comment]
After updating the store data (something like `accordion.store.data = accordion.store.data.splice(0,6);`), the selectionModel should be empty.
