### ISSUE TITLE
Design Token conversion script should consider color modifications

### ISSUE THREAD

**Issue by mxmrtns** [neomjs/neo#5094]
As shown in the link below, the JSON export from Token Studio includes the color modifications made in Figma.

Currently. the script can't interpret this description correctly and outputs incorrect variables.

Feature request:
The conversion script should be able to interpret the color modifications and output the corresponding SCSS variables.

https://github.com/neomjs/neo/blob/92ab05e27b02de30cc5630ce99dbc7a68fd4a61f/resources/design-tokens/json/core.json#L1

Relevant parameter are:

type: darken or lighten
value: 0-1
space: hsl, srgb, p3, lch

**Comment by tobiu** [comment]
pushed a WIP version.

are the real values always inside the "500" key? or can it be anywhere in therory?

first result:
<img width="1186" alt="Screenshot 2023-11-13 at 19 23 08" src="https://github.com/neomjs/neo/assets/1177434/55b77e9b-2e91-4381-8518-238d0ab66265">

**Comment by tobiu** [comment]
@mxmrtns: here is a full list of what we can use with SCSS:
https://sass-lang.com/documentation/modules/color/#darken

e.g. `darken()` is no longer recommended, but `color.scale()` is.

```
@use 'sass:color';

// #036 has lightness 20%, so when darken() subtracts 30% it just returns black.
@debug darken(#036, 30%); // black

// scale() instead makes it 30% darker than it was originally.
@debug color.scale(#036, $lightness: -30%); // #002447
```
