### ISSUE TITLE
form.field.Date: shows the native picker when using the space key

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5217]
i noticed that pressing enter does show the neo picker. maybe we could just convert space into enter in this case, but open for other solutions.

**Comment by mxmrtns** [comment]
Hi @tobiu, please make sure to always comply with the WCAG guideline here. For example the picker should show when pressing Enter OR Space
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/

**Comment by tobiu** [comment]
hi @mxmrtns, correct, when we fix space, the neo picker should show for enter & space in the same way.

i moved the a11y topic into another ticket: https://github.com/neomjs/neo/issues/5219
