### ISSUE TITLE
Portal.view.learn.PageContainer: Footer Button on first page

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5350]
Assuming this one should not take the full width, but the last 50%.

<img width="1528" alt="Screenshot 2024-03-17 at 14 21 53" src="https://github.com/neomjs/neo/assets/1177434/2ed73414-4f32-41ac-9257-18568a34406f">

**Comment by Michael-Nwachukwu** [comment]
hey @tobiu, can i work on this?

**Comment by tobiu** [comment]
hi @Michael-Nwachukwu!

it depends on how @mxmrtns wants the footer to look like.

the JS code is here: https://github.com/neomjs/neo/blob/dev/apps/portal/view/learn/PageContainer.mjs

the logic is data-driven: in case there is no `previousPageRecord`, the last page button will get the `hidden` config set to true, which then won't render it into the DOM at all.

the related SCSS is here: https://github.com/neomjs/neo/blob/dev/resources/scss/src/apps/portal/learn/MainContainer.scss#L20

a button has `flex: 1` which is fine in case there are 2 buttons, but not so much in case there is just one.

the chicken and egg problem: the ticket is related to the new learning section, which you will need to actually understand how the framework works and more importantly how to use it as a developer. we need around 4 more weeks to publish the new portal app.

you could create a fork, run `npm i`, then `npm run build-all`, then ideally enable the theme watcher: `npm run watch-themes` to get your SCSS compiled into CSS when doing changes. afterwards `npm run server-start` and open the portal app inside the browser.

my recommendation would be: join the slack channel first. @maxrahder is moderating weekly workshops and can help interested devs in getting up to speed.

**Comment by Michael-Nwachukwu** [comment]
Hi @tobiu can i get a link to the slack channel? I just took a look and i indeed need to understand the framework first.

**Comment by tobiu** [comment]
here is the link: https://join.slack.com/t/neomjs/shared_invite/zt-6c50ueeu-3E1~M4T9xkNnb~M_prEEOA
