### ISSUE TITLE
Theme neo light: splitter scss file needs a cleanup

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5363]
related to: https://github.com/neomjs/neo/issues/5362

for some of the overrides, we already have theming vars. e.g. `background-color`.

for other rules, new theming vars probably make sense.

see:
https://github.com/neomjs/neo/blob/dev/resources/scss/src/component/Splitter.scss
https://github.com/neomjs/neo/blob/dev/resources/scss/theme-neo-light/component/Splitter.scss

@mxmrtns

**Comment by sarfarazsiddiquii** [comment]
hi @tobiu can i work on this issue, i think i can fix this.
