### ISSUE TITLE
Portal.view.HeaderToolbar: separate bar limited to home

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5611]
Inside the Portal App home page, the separate bar slides out to the right when scrolling downwards.

This is not the case for all other pages, e.g. the learning section.

![Screenshot 2024-07-21 at 17 29 35](https://github.com/user-attachments/assets/1710451e-5bc7-464d-8a05-195c77054ba0)

**Comment by Dinkh** [comment]
Fixed for blog, learn, services
