### ISSUE TITLE
Portal.view.HeaderToolbar: separate bar => triggers fadeIn / fadeOut animations for scrolling child nodes inside Home

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5642]
https://github.com/user-attachments/assets/1e06b077-222a-4852-a050-aed483e87188

Obviously the separate-bar should only show / hide when scrolling the main container.

**Comment by Dinkh** [comment]
Fixed.
The problem is, that the domListener for scroll captures any component inside the MainContainer, instead of checking for the correct target.
