### ISSUE TITLE
component.Video: handleAutoplay() => redundant update() call

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5676]
If I see it correctly, `handleAutoplay()` only gets called inside `construct()`. If so, the method needs the `@protected` flag.

It is using `this.update()` before changing the value of the playing config, which itself also triggers an `update()` call.

We really want to batch all changes into one `update()` call instead => removing it inside `handleAutoplay()` would be sufficient.

Rationale: `update()` sends the vdom & vnode on a workers roundtrip to get the deltas. While this is happening, the component locks itself for future updates until the new vnode got back (async). After the delay the framework would trigger a 2nd roundtrip to get the deltas for the visible node.

**Comment by Dinkh** [comment]
understood and fixed
