### ISSUE TITLE
component.Video: remove beforeSetPlaying()

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5677]
```
    beforeSetPlaying(value, oldValue) {
        if (!Neo.isBoolean(value)) {
            return oldValue
        }

        return value
    }
```

Validating a boolean on class level is pointless. Doing a check for specific enum values is fine, but when it comes to base types, this is way over the top. Imagine we would add `beforeSetX()` for every possible boolean, number or string config inside the framework.

We can think about generic config type checkings, but this is not the way to go.

**Comment by Dinkh** [comment]
removed
