### ISSUE TITLE
update npx neo-app MyApp example to "export default Neo.setupClass(...)" 

### ISSUE THREAD

**Issue by gplanansky** [neomjs/neo#5840]
**to fix:**  npx neo-app _MyApp_ example", which broke with the 7.0.3 change to "export default Neo.setupClass(<classname>)" usage.

**old usage breaks:**
```
Neo.applyClassConfig(MainContainer);

export default MainContainer;

```
**new usage:**
`export default Neo.setupClass(MainContainer);`

**See:**
https://github.com/neomjs/neo/blob/c70ce319114232d83c2f146005b7e14abac42ed3/buildScripts/tools/createExample.mjs#L153

**Comment by tobiu** [comment]
makes sense.

the breaking part was: https://github.com/neomjs/neo/issues/5817

**Comment by tobiu** [comment]
https://github.com/neomjs/create-app/commit/1ccfaf42a1bfb188d3792e4ccdf101a42097f9a6
https://github.com/neomjs/create-app/commit/a04b327bbd791f3aee99e867a44581d1d82a34ed

**Comment by tobiu** [comment]
i will add a new ticket for the create example script which @ThorstenRaab created.
