### ISSUE TITLE
fix classname typo in  examples/todoList/version2/TodoListModel.mjs

### ISSUE THREAD

**Issue by gplanansky** [neomjs/neo#5858]
fix typo  

https://github.com/neomjs/neo/blob/62b219027e5404054eb1cd843eea6656411f4bcf/examples/todoList/version2/TodoListModel.mjs#L9C5-L9C65

 "MainModel" should read "TodoListModel":

`className  : 'Neo.examples.todoList.version2.MainModel',`    --> 
`className  : 'Neo.examples.todoList.version2.TodoListModel',`

**Comment by tobiu** [comment]
fair point. assigning it to you :)

**Comment by tobiu** [comment]
resolved. thx!
