### ISSUE TITLE
Examples sometimes fail to load

### ISSUE THREAD

**Issue by jzombie** [neomjs/neo#5899]
**Describe the bug**

Getting a "white screen" when first navigating to https://neomjs.com/dist/production/apps/portal/#/examples.

My apologies, I didn't capture any debug logs or a screenshot.

Happened in Chrome on Mac, from Nicaragua. 

**To Reproduce**

This is tricky because I can't reproduce it, even in Incognito or in Firefox, but it's happened in the past as well on Chrome.

**Expected behavior**

To be able to view content.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  macOS 13.6.7
 - Browser:  Chrome 
 - Version: 128.0.6613.120 

**Additional context**
My apologies I didn't capture a screenshot.  I originally did and was going to post it on LinkedIn, but decided that a bug report was more appropriate.  In the process, I deleted the screenshot that I took, and now can't seem to reproduce it.

**Comment by tobiu** [comment]
Hi Jeremy ( @jzombie ),

thanks for the input! I think this is related to the service worker (caching). In case I do deploy a new version, the SW get notified and clears the entire cash. However, at this point it probably already is too late and some old files have been loaded.

A reload will already fix it, but I do agree that this is not a nice UX. What we can / should do: In case the SW gets the new version notification, it should tell the connected app about it => opening an alert / dialog, telling the user that a new version is available and a reload is required.

Thoughts?

Best regards,
Tobi

**Comment by jzombie** [comment]
My thoughts are that if the page isn't loading at all, it should do a force reload, if that's possible.  There was no content on the page at all.

**Comment by tobiu** [comment]
From a technical perspective, it has to be this spot:
https://github.com/neomjs/neo/blob/dev/src/worker/ServiceBase.mjs#L252

If the version did change, we need to send back a `versionChange` message. This could either be a direct message or a broadcast to all connected clients. When receiving it, we can trigger a notification or reload.

**Comment by tobiu** [comment]
Hi Jeremy,

the "force reload when a SW gets a new version" is in place now. crossed fingers :)

While creating the changes, I managed to create an infinite reload loop (classic). So I learned how to kill a SW instance from a non-connected window.

Feel free to take a look into the commit.

Best regards,
Tobi
