### ISSUE TITLE
7.3.0 release   examples/dialog <Esc> does not hide dialog after dialog is dragged

### ISSUE THREAD

**Issue by gplanansky** [neomjs/neo#5901]
**Describe the bug**
examples/dialog  <Esc> does not hide dialog after mouse click on dialog, or, dialog moved

**To Reproduce**
git clone,  cd neo, npi i, npm run build-all, npm run server-start
chrome:   run examples/dialog

1. works:
reload
click create dialog button   --> dialog appears
\<Esc\>   --> dialog hides 

2. not works:
reload
click create dialog button   --> dialog appears
click or drag dialog
\<Esc \>  -->  dialog unchanged 

**Expected behavior**
the (1) works case above

**Desktop (please complete the following information):**
 - OS: macos 15.6
 - Browser  Chrome Version 128.0.6613.138 (Official Build) (arm64)

**Comment by tobiu** [comment]
typing too fast. "re-focussing" should have been the commit message title^^

since we now re-apply the focus after drag & resize OPs, the ticket is resolved.
