### ISSUE TITLE
7.3.0  examples/grid/container  all highlighting fails

### ISSUE THREAD

**Issue by gplanansky** [neomjs/neo#5910]
**Describe the bug**
dev 7.3.0  examples/grid/container  all highlighting fails
rows focus on mouse, but mouse clicks do not highlight in any selection mode

This works in on my 6.10.10 install.

**To Reproduce**
git clone, etc
npm run server-start
chrome -->  examples/grid/container

**Expected behavior**
highlighting per various selection modes works

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: Version 128.0.6613.138 (Official Build) (arm64)

**Comment by gplanansky** [comment]
ditto for examples/table/container

**Comment by tobiu** [comment]
let's break this one up into smaller tickets.

**Comment by tobiu** [comment]
resolved via the tickets 5911 to 5924.

i wanted to add the new listeners to the selection models anyway ;)

the grid is still experimental, i would not recommend using it before the buffered rendering is in place. @rwaters 

be aware that the event signature changed a bit for the rowClick & cellClick events => data contains new top level infos (e.g. record & field), the original received event is passed inside `data.data`.
