### ISSUE TITLE
Welcome to the Hacktoberfest 2024!

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5963]
The event is starting soon (October 1-31) and the registration just opened:
https://hacktoberfest.com/

Since you are reading this: congratulations, you have found a hidden gem repo :)

A quick (outdated) intro:
<p align="center">
    <a href="https://youtu.be/pYfM28Pz6_0"><img height="316px" width="400px" src="https://raw.githubusercontent.com/neomjs/pages/master/resources_pub/images/neo33s.png"></a>
    <a href="https://youtu.be/aEA5333WiWY"><img height="316px" width="400px" src="https://raw.githubusercontent.com/neomjs/pages/master/resources_pub/images/neo-movie.png"></a>
</p>

Neo.mjs made it into the Top5 of the category "The most exciting use of technology in 2021" (OS awards program).
Afterwards, the project stayed mostly off the grid and evolved in silence.

The timing is perfect, since we literally just finished the new project website which includes a first learning section:
https://neomjs.com/

In general, we value the following 2 items exactly the same:
* Non-technical contributions
* Technical contributions

## The Neo.mjs team is here to support you

We are doing weekly workshops on Thursdays 18:30 CEST (12:30am EST) for 60m free of charge.

You are very welcome to join us on Slack: <a href="https://join.slack.com/t/neomjs/shared_invite/zt-6c50ueeu-3E1~M4T9xkNnb~M_prEEOA">Neo.mjs Slack Channel</a>
or on Discord: <a href="https://discord.gg/6p8paPq">Neo.mjs Discord Channel</a>

Hint: There are by far more users on Slack, but both works.

We will create some first example tickets soon. You are also very much welcome to create your own tickets, just please wait until they got approved before working on them.

Welcome to the Neo.mjs community & happy contributing,
Tobias

**Comment by botoxparty** [comment]
Commenting to subscribe! Would love to participate.

**Comment by gplanansky** [comment]
Welcome.   Here's an idea for _**computer science student projects**._  .

Neo is a full-fledged front-end framework that uniquely delivers on advanced features, yes.   

But you can also use it as a **_reference implementation of 2024 web standards_** --  its multi-thread / web worker architecture  enables the cool features  and  _**_the code is very hackable._**_    

If you want to explore aspects of the core architecture, implement and test approaches,  perhaps explore a novel application -- and **_make a student project of it for your course work -- go for it_**. 
 
We can work with you and your instructors, get you started.

**Comment by Mialy333** [comment]
Hi! 👋 I'd love to take part of your projects! Especially for writing tests. So if you still need test writing, please assign me to any project. Otherwise, I'm interest to contribute to any tasks you need to be done.

**Comment by tobiu** [comment]
@Mialy333: Hi and welcome!

Testing tickets for the hacktoberfest scope are still untouched. We could easily create 100+ tickets in this area, if needed.

As an easy warm up-ticket, this one could work: https://github.com/neomjs/neo/issues/6029

Add a comment there, in case you would like to give it a try.

Best regards,
Tobi

**Comment by Mialy333** [comment]
Ok for the ticket #6029, you can assign me to it

**Comment by tobiu** [comment]
Since the event has ended, i will close all hacktoberfest related tickets now. In case someone still wants to work on a related ticket, feel free to add a comment and we can reopen it.
