### ISSUE TITLE
Write a new guide or tutorial for the learning section content

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5965]
Related to: https://github.com/neomjs/neo/issues/5963 (Please read this ticket first)

You can find the new learning section here:
https://neomjs.com/dist/production/apps/portal/#/learn/benefits.Multi-Threading

It would help a lot in case the community would support us with creating more content for the learning section.

In case you know areas where more guides are needed, but don't know the framework well enough to write the article yourself, please open new feature request tickets.

We can make the deal: Opening 5 new tickets which get confirmed is worth a hacktoberfest PR.

**Comment by NishantSinghhhhh** [comment]
Can you assign this issue to me, I am very much motivated to do this one

**Comment by NishantSinghhhhh** [comment]
Can you Assign this issue to me ??

**Comment by tobiu** [comment]
Hi and welcome @NishantSinghhhhh,

as mentioned inside the ticket description, this is a bulk-info-ticket. I guess we could easily create 50 - 100 new guides, in case we want to cover all areas of the Neo.mjs framework.

Call to action: pick an area which you want to write about, then we can create a new specific ticket and assign it to you.

Some ideas for areas:
* Working with `Neo.table.Container`
* Working with `Neo.tab.Container`
* Container Layouts
* Creating a form in Neo
* Working with a main thread addon
* Creating your first app
* Creating a custom component

For getting up to speed and finding more areas, I can recommend to walk through the following tutorial:
https://neomjs.com/dist/production/apps/portal/#/learn/tutorials.Earthquakes

Best regards,
Tobi

**Comment by NishantSinghhhhh** [comment]
I can work with creating a form and a custom component, so can I begin working with it .

I have used neo.mjs once so I am comfortable using it

**Comment by tobiu** [comment]
@NishantSinghhhhh: I just created the new ticket here:
https://github.com/neomjs/neo/issues/6009

I think you need to add a comment, otherwise I can not assign it to you.

Off topic:
https://github.blog/changelog/2024-10-01-evolving-github-issues-public-preview/
=> I signed the repo up for the waiting list. sub-issues would be super helpful for bulk tickets like this one. No clue how long it takes though to get the early access.

**Comment by tobiu** [comment]
we already got unlocked for the beta sub issues. just tested it with adding the forms guide ticket as a child to this one.

**Comment by tobiu** [comment]
Since the event has ended, i will close all hacktoberfest related tickets now. In case someone still wants to work on a related ticket, feel free to add a comment and we can reopen it.
