### ISSUE TITLE
Create a new Design Theme

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5966]
Related to: https://github.com/neomjs/neo/issues/5963 (Please read this ticket first)

A call to all designers who would like to participate in hacktoberfest.

Obviously creating an entire theme is a big epic. We can split it up fairly easily: every component / widget is worth a separate pull request.

**Comment by vanshajkataria** [comment]
@tobiu 
Can I please work on this issue?

**Comment by tobiu** [comment]
@vanshajkataria you are welcome to create a sub-issue on your own. otherwise i need a title for it (e.g. the theme name, color palette), but then you need to add a comment there, otherwise i can not assign it.

**Comment by vanshajkataria** [comment]
@tobiu Okay, Understood!
I will get back to you with a sub-issue in some time.

**Comment by petercr** [comment]
This sounds great, maybe we should try to open the issue(s) first as well. 
That way people won't end up working on the same design feature at the same time.
