### ISSUE TITLE
Neo Website Home Section

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#6008]
Related to the Hacktoberfest Welcome ticket: https://github.com/neomjs/neo/issues/5963 (Please read this ticket first)

Another shout-out to all designers who would like to participate in the hacktoberfest event.

![Screenshot 2024-10-02 at 15 58 12](https://github.com/user-attachments/assets/bc3fb956-b71f-46bf-83ea-fee09996fe42)

The very first page when opening the Neo.mjs website still looks odd.

@mxmrtns had the idea to make the tag-line the biggest element, the logo smaller on top and the content text centered.
Rationale: Neo.mjs is not yet a known brand, so the tag-line provides the most value.

Maybe it could go a bit into this direction: https://nuxt.com/

Looking forward to your ideas!

Thanks in advance,
Tobi

**Comment by TusharMohapatra07** [comment]
I would like to work on this. Please assign me this issue.

**Comment by tobiu** [comment]
sure. looking forward to your ideas.

hint: you could either use a design tool like figma or play with the current CSS. the specific file is located here:
https://github.com/neomjs/neo/blob/dev/resources/scss/src/apps/portal/home/parts/MainNeo.scss

**Comment by tobiu** [comment]
Since the event has ended, i will close all hacktoberfest related tickets now. In case someone still wants to work on a related ticket, feel free to add a comment and we can reopen it.
