### ISSUE TITLE
Learning Section Content: Create a Guide on using forms

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#6009]
It would be nice to cover multiple different field types and fieldsets.

I already created a short intro-article on forms:
https://neomjs.com/dist/production/apps/portal/#/learn/benefits.FormsEngine

I also created an example on nested lazy-loaded forms:
https://github.com/neomjs/neo/tree/dev/apps/form

Learning Section Content is written in markdown. To get the idea (including using code live-previews):
https://raw.githubusercontent.com/neomjs/neo/refs/heads/dev/resources/data/deck/learnneo/pages/benefits/FormsEngine.md

**Comment by NishantSinghhhhh** [comment]
I want to Contribute in this Issue @tobiu

**Comment by tobiu** [comment]
I was right on my theory. Now I could assign it to you :)

Feel free to ping us on Slack, in case you need help.

**Comment by tobiu** [comment]
thinking more about it: you could also create an example / an app inside the framework (separate hacktoberfest PR) for the forms guide and reference it. as you like.

**Comment by NishantSinghhhhh** [comment]
@tobiu  I have added a PR for the Forms Engine Section , Please review it , if any change need to be done on that commit , do let me know , I will be more than happy to do the changes , I am eagerly waiting to work on the next issue #6009

**Comment by tobiu** [comment]
Since the event has ended, i will close all hacktoberfest related tickets now. In case someone still wants to work on a related ticket, feel free to add a comment and we can reopen it.
