### ISSUE TITLE
Improvement Design ofFooter Section

### ISSUE THREAD

**Issue by MrunalKashid02** [neomjs/neo#6022]
![Image](https://github.com/user-attachments/assets/c44095a2-7111-45ce-b3a6-6f64af4ebfa6)

Design of Footer Section can be Improved.

**Comment by tobiu** [comment]
looking forward to your ideas. hint: i would start with a visual concept, before writing code (worth a hacktoberfest PR).

one requirement for the footer is responsiveness => it has to work on desktop & mobile.

best regards,
tobi

**Comment by tobiu** [comment]
Since the event has ended, i will close all hacktoberfest related tickets now. In case someone still wants to work on a related ticket, feel free to add a comment and we can reopen it.
