### ISSUE TITLE
Improvement Blog page's design and layout

### ISSUE THREAD

**Issue by SaiAryan1784** [neomjs/neo#6024]
I would like to redesign and implement that design in the blog page so that it looks mordern and better.

Please assign me this task so that i can work on it as soon as possible.

@tobiu

**Comment by ayush-343** [comment]
I would like to improve and redesign of the blog page making it more modern and interactive
Please assign me this task 
 @tobiu

**Comment by tobiu** [comment]
Since the event has ended, i will close all hacktoberfest related tickets now. In case someone still wants to work on a related ticket, feel free to add a comment and we can reopen it.
