### ISSUE TITLE
Component Tests: Button

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#6029]
We already have a starting point:
https://github.com/neomjs/neo/tree/dev/test/components/files/button

This can get extended to test more config options, especially changing configs at run-time.

Some configs which are worth to get tested:
1. text
2. iconCls
3. iconPosition
4. badgeText
5. badgePosition
6. route

**Comment by Mialy333** [comment]
Hi 👋🏽
Could you please assign me to this task please? I'm already working on it. Thanks ! 
Best,
Mialy

**Comment by tobiu** [comment]
now i can => it does require a comment inside the same ticket, otherwise devs do not show up inside the assignees list.

some background infos:
* the apps & components which we want to test live within the app worker
* the testing tool (siesta) runs inside the main thread
* since there are no testing tools yet which can run inside a web worker, we do need async helper methods to create or modify neo instances from within the main thread.

if you want to get a better understanding how you would normally build apps:
https://neomjs.com/dist/production/apps/portal/#/learn/tutorials.Earthquakes

best regards,
tobi

**Comment by tobiu** [comment]
Since the event has ended, i will close all hacktoberfest related tickets now. In case someone still wants to work on a related ticket, feel free to add a comment and we can reopen it.
