### ISSUE TITLE
table.View.onStoreRecordChange fields do not match  selectedRecordField - bug  and  fix

### ISSUE THREAD

**Issue by gplanansky** [neomjs/neo#6041]
table.View.onStoreRecordChange
see neo 7.16 dev
https://github.com/neomjs/neo/blob/0ac043b1d124206c17383d37a9bdd1c055bb7980/src/table/View.mjs#L480

**Symptom**:   Table rows did not change their row highlighting after a `record.annotation.selected ` (boolean) value change .

**Background**:   

table.View has a config property `selectedRecordField` whose string value, say 'annotation.selected' is
designed to correspond to a corresponding table  data record field:   
```js
record.annotation -> { 'annotation' { selected : true/false }} 
```
The approach allows flexibility to use other annotation sub fields,  specifying which are in play via a string config property.

It requires 

* a way to use a dotted string  to retrieve a record value, using the field.name value.   
        View ingeniously does this elsewhere with with Neo.ns.  
*  getting and matching the changed field's name
* getting and matching the changed field's value.

For the above test example,  however, Store gives us a `field.name` value of "annotation", not "annotation.selected" .   That is, Store tells us which record fields have changed, not which record  subfields.     Being consistent, Store also has  the `field.value` as {selected: false}  instead of false.  

**bug**

Processing the `selectedRecordField` the logic 
1. failed to match  the field.name   -- L 479 
2. failed to get the value of the changed field -- L 481
3. was stuck by `selection.Model.singleselect == false,` at the `'select'` branch -- L 481

https://github.com/neomjs/neo/blob/0ac043b1d124206c17383d37a9bdd1c055bb7980/src/table/View.mjs#L480

** bug fix / workaround**

This patch ( against 6.17 dev a day ago)  provides fixes / workarounds: 
```
diff View.mjs View.mjs.orig

479,480c479
<                  if (field.name === me.selectedRecordField.split('.')[0]) {
<                     let selectedFieldValue = Neo.ns(me.selectedRecordField,false,record);
---
>                 if (field.name === me.selectedRecordField) {
482c481
<                         selectionModel[!selectedFieldValue? 'deselect' : 'select'](me.getRowId(record))
---
>                         selectionModel[!field.value && selectionModel.singleSelect ? 'deselect' : 'select'](me.getRowId(record))
```

**comments*  

* Not sure why `singleSelect` was in the logic here.
* Also have to restore the  desired scroll to the changed row behavior.

**Comment by tobiu** [comment]
george, you do have the following example on which i spent multiple hours just for you to see how it is working:
https://neomjs.com/examples/table/nestedRecordFields/index.html

looking at your desired change: `if (field.name === me.selectedRecordField.split('.')[0]) {`

it can only assume(!) that you are doing something like:
```
record.annotations = {selected: true};
```

i know max did that inside the trainings before we had change events for nested fields, but this is clearly not the way to go. we do not want to listen to changes of any possible annotations, but to the the "right" one.

meaning (as it is done inside the example):
```
record.annotations.selected = true;
```

the singleSelect part should indeed move somewhere else.

**Comment by gplanansky** [comment]
as I recall from a year and more back, the assignment 
```
record.annotations.selected = true
```

failed,  because  Store couldn't handle the case where there was not (yet) a record.annotations field.   

More generally, at the time Store could not completely handle  nested fields.  At the time I used some some tricky dribbling to handle that case, essentially constructing that object on the fly, yet without obliterationg  other potentially existing key:value pairs.

In the  workshop discussion, you confirmed the store limitation, and  advised exactly the same solution.   So that was the right way at the time.  You also wondered out loud,  whether you should modify store to handle nested fields so the above assignment would work, and, how deep you should support such nesting,  

Re your comment:

_i know max did that inside the trainings before we had change events for nested fields, but this is clearly not the way to go. we do not want to listen to changes of any possible annotations, but to the the "right" one._

I don't recall what Max did, just what I did.  As to what is "right", that is an idiosyncratic moral qualifier.   I prefer "what works".   My code listened for a record change signal and did not have to know further, from the event information, exactly what field value had changed.  Indeed, my application code knew what it was changing, so it could looked for that change.   

In contrast, your View.js code requires knowing from the Store event exactly what field has changed.  However your Store implementation limits that information to limited spec that you decided on _but did Not document_.   Consequently, I could not use View.js, without changing it.   

The bug report said what did not work and why, as best as I could tell.  IF you have fixed Store, so it accepts the assignment operation, you should have documented that welcome improvement in the change notes.   
 
The json file format in play, which store duly reads in,  is as simple as it gets.

```
cat  earthquakes.json. 
{
  "results":[
    {
     "annotation": {"selected": true},
     "timestamp":"2017-10-13T12:07:24.000Z",
     "latitude":63.976,
     "longitude":-21.949,
     "depth":1.1,
     "size":0.6,
     "quality":58.73,
     "humanReadableLocation":"6,1 km SV af Helgafelli"
   },
```
