### ISSUE TITLE
Documentation quick navigation buttons non-responsive after filtering

### ISSUE THREAD

**Issue by keckeroo** [neomjs/neo#650]
**Describe the bug**
When filtering / unfiltering a classes private and static methods, the Section 'quick navigation' buttons become non responsive

**To Reproduce**
1. Navigate to Neo.form.field.trigger.Date in neo docs
2. Uncheck 'Private' Filter
3. Check 'Private' Filter
4. Click [Methods] button

**Expected behavior**
Docs should scroll down to methods section

**Actual behaviour**
Nothing happens

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Chrome
 - Version 81.0

**Comment by tobiu** [comment]
please double check this one kevin :)
