### ISSUE TITLE
RealWorld app: Create Post

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#68]
RealWorld.views.article.CreateComponent

Similar to Sign In:
1) fetch the form data
2) show errors
3) TagField: (cls: ['tag-list'])
3.1) add tags (onKeyDownEnter)
3.2) prevent adding tags with the same name
3.3) tags should be closable
4) RealWorld.api.Article => post()

**Comment by mrsunshine** [comment]
@tobiu please at the value='' reset for the tag field after enter

**Comment by tobiu** [comment]
done.
