### ISSUE TITLE
neo website: design

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#840]
i am most definitely not a designer, so i could use your help on this part.

mostly focussing on getting the website app functional first.

![Screenshot 2020-07-01 at 00 18 52](https://user-images.githubusercontent.com/1177434/86185807-8eb45600-bb37-11ea-8f20-2aa3fe931a9d.png)

![Screenshot 2020-07-01 at 00 19 08](https://user-images.githubusercontent.com/1177434/86185817-970c9100-bb37-11ea-8f0a-b5b1f288163f.png)

thx & best regards,
tobias

**Comment by adriantoddross** [comment]
Hey there! I came across this PR when looking for help-wanted & good first issue.

Can you tell me more about what you're looking for? Is the image above an example of what you want the site to look like or are you looking for someone to propose a new website design altogether?

**Comment by tobiu** [comment]
Hi Adrian,

the images are already the work in progress version. History: the project started with a standard GitHub template:

https://neomjs.github.io/pages/

More and more content got in and it just looks terrible.

To close this gap, it started working on a new version (see the images above). This one is already online here:

https://neomjs.github.io/pages/node_modules/neo.mjs/apps/website/index.html#mainview=blog

It is not responsive yet (so you can not look at it on a phone yet) => use a desktop env, ideally Chrome, but it should run in FF, Safari & Edge as well.

Starting on Sunday, making it responsive is the next item on my todo list.

Since I am not a designer, I am sticking to making it functional first.

If someone with more advanced design skills would create a new layout, this would be appreciated. You can basically throw any design concept at me and I can make it work using CSS, so you don't have to be a pro using CSS. Photoshop skills (or your tool of choice) are enough.

In case someone comes up with a new design which we are going to use, we can definitely add a backlink to the page footer: like "design sponsored by XY => link to a company page or linked in profile).

The same goes for a new logo.

Best regards,
Tobias

**Comment by tobiu** [comment]
current version:
![Screenshot 2020-07-05 at 20 55 57](https://user-images.githubusercontent.com/1177434/86541328-44065580-bf0c-11ea-8e26-b5507e6bdd82.png)

![Screenshot 2020-07-05 at 20 59 19](https://user-images.githubusercontent.com/1177434/86541332-4963a000-bf0c-11ea-9051-78f868f4d8ef.png)

https://www.youtube.com/watch?v=aVHvvbsMQGA
